version: "3.3"
services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - plausible

  plausible:
    labels:
      virtual.host: ${VIRTUAL_HOST}
      virtual.port: ${VIRTUAL_PORT}
      virtual.tls-email: ${VIRTUAL_TLS_EMAIL}
        
volumes:
    caddy-certificates:
        driver: local
